INCLUDE "includes.asm"

MACRO test_constant
	PRINTLN "\1={d:\1}"
ENDM
	test_constant THUNDERBOLT
	test_constant SURF
	test_constant THUNDER_WAVE
	test_constant QUICK_ATTACK
	test_constant PIKACHU
	test_constant RAICHU
	test_constant EEVEE
	test_constant PARTYMON_STRUCT_LENGTH
	test_constant BOXMON_STRUCT_LENGTH
	test_constant EVENT_GOT_BILLS_GARDEN_PIKACHU
	test_constant RECOVER
	test_constant SOFTBOILED
	test_constant REST
	test_constant HAS_SUBSTITUTE_UP
	test_constant NORMAL
	test_constant FIGHTING
	test_constant FLYING
	test_constant POISON
	test_constant GROUND
	test_constant ROCK
	test_constant BUG
	test_constant GHOST
	test_constant FIRE
	test_constant WATER
	test_constant GRASS
	test_constant ELECTRIC
	test_constant PSYCHIC_TYPE
	test_constant ICE
	test_constant DRAGON
	test_constant NO_EFFECT
	test_constant NOT_VERY_EFFECTIVE
	test_constant EFFECTIVE
	test_constant SUPER_EFFECTIVE
	test_constant AGILITY
	test_constant PSYCHIC_M
	test_constant ICE_BEAM
	test_constant EMBER
	test_constant INVULNERABLE
	test_constant TRANSFORMED
	test_constant DITTO
	test_constant UNDERGROUND_PATH_WEST_EAST
	test_constant BIT_CUR_MAP_LOADED_1
	test_constant EVENT_BEAT_ROCKET_HIDEOUT_GIOVANNI
	test_constant EVENT_BEAT_SILPH_CO_GIOVANNI
	test_constant EVENT_BEAT_UNDERGROUND_PATH_ROCKET_DESERTER
	test_constant TOGGLE_UNDERGROUND_PATH_ROCKET_DESERTER
	test_constant TOGGLE_UNDERGROUND_PATH_DISCARDED_UNIFORM
