INCLUDE "includes.asm"

MACRO test_constant
	PRINTLN "\1={d:\1}"
ENDM
	test_constant THUNDERBOLT
	test_constant SURF
	test_constant THUNDER_WAVE
	test_constant QUICK_ATTACK
	test_constant PIKACHU
	test_constant RAICHU
	test_constant EEVEE
	test_constant PARTYMON_STRUCT_LENGTH
	test_constant BOXMON_STRUCT_LENGTH
	test_constant EVENT_GOT_BILLS_GARDEN_PIKACHU
	test_constant RECOVER
	test_constant SOFTBOILED
	test_constant REST
	test_constant HAS_SUBSTITUTE_UP
	test_constant NORMAL
	test_constant FIGHTING
	test_constant FLYING
	test_constant POISON
	test_constant GROUND
	test_constant ROCK
	test_constant BUG
	test_constant GHOST
	test_constant FIRE
	test_constant WATER
	test_constant GRASS
	test_constant ELECTRIC
	test_constant PSYCHIC_TYPE
	test_constant ICE
	test_constant DRAGON
	test_constant NO_EFFECT
	test_constant NOT_VERY_EFFECTIVE
	test_constant EFFECTIVE
	test_constant SUPER_EFFECTIVE
	test_constant AGILITY
	test_constant PSYCHIC_M
	test_constant ICE_BEAM
	test_constant EMBER
	test_constant INVULNERABLE
	test_constant TRANSFORMED
	test_constant DITTO
	test_constant UNDERGROUND_PATH_WEST_EAST
	test_constant ROUTE_12
	test_constant BIT_CUR_MAP_LOADED_1
	test_constant EVENT_BEAT_ROCKET_HIDEOUT_GIOVANNI
	test_constant EVENT_BEAT_SILPH_CO_GIOVANNI
	test_constant EVENT_BEAT_UNDERGROUND_PATH_ROCKET_DESERTER
	test_constant TOGGLE_UNDERGROUND_PATH_ROCKET_DESERTER
	test_constant TOGGLE_UNDERGROUND_PATH_DISCARDED_UNIFORM
	test_constant EVENT_BEAT_VERMILION_DOCK_MEW
	test_constant EVENT_MOVED_VERMILION_DOCK_TRUCK
	test_constant DEX_MEW
	test_constant MEW
	test_constant EVENT_BEAT_LAVENDER_WHITE_HAND
	test_constant EVENT_BEAT_MANSION_DITTO
	test_constant EVENT_BEAT_SEAFOAM_WHIRLPOOL_GYARADOS
	test_constant EVENT_BEAT_FUCHSIA_ESCAPED_RHYHORN
	test_constant EVENT_FUCHSIA_RHYHORN_ESCAPED
	test_constant EVENT_SAW_FUCHSIA_RHYHORN_ESCAPE
	test_constant TOGGLE_FUCHSIA_CITY_ESCAPED_RHYHORN
	test_constant TOGGLE_FUCHSIA_CITY_CHASING_WARDEN
	test_constant TOGGLE_BILLS_SECRET_GARDEN_PIKACHU
	test_constant EVENT_BEAT_MT_MOON_EXIT_SUPER_NERD
	test_constant EVENT_COMPLETED_MT_MOON_MOONFALL_CEREMONY
	test_constant TOGGLE_MT_MOON_1F_ITEM_2
	test_constant MOON_STONE
	test_constant POTION
	test_constant DEX_PIKACHU
	test_constant BIT_BEAT_ELITE_4
	test_constant EVENT_SS_ANNE_LEFT
	test_constant EVENT_BEAT_VERMILION_DOCK_GHOST_SAILOR

SECTION "Test Route 12 object constants", ROMX
INCLUDE "data/maps/objects/Route12.asm"
	test_constant ROUTE12_REFORMED_FISHER
	test_constant ROUTE12_RATICATE
